version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: tareas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tareas_user
      POSTGRES_PASSWORD: tareas_pass
      POSTGRES_DB: tareas_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tareas_app
    environment:
      DATABASE_URL: postgres://tareas_user:tareas_pass@postgres:5432/tareas_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres_data: